version: '3'
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=********
      - DB_USER=********
      - DB_PASSWD=********
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "33:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=********
      - MYSQL_DATABASE=********
      - MYSQL_USER=********
      - MYSQL_PASSWORD=********
    volumes:
      - ./db/:/var/lib/mysql
  jenkins:
      image: jenkins/jenkins:lts
      user: root
      ports:
        - 8080:8080
      volumes:
        - ./jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock 
        - /usr/bin/docker:/usr/local/bin/docker
